version: "3.8"

x-base: &base
  build:
    dockerfile: ./docker_dev/Dockerfile
    context: .
services:
  web:
    <<: *base
    restart: on-failure
    volumes:
      - .:/app
    command: npm run dev
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      HOST: 0.0.0.0
